### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds a button to get your app via the [IzzyOnDroid open source app repo](https://apt.izzysoft.de/fdroid/) in a F-Droid client.

It will help people without Google Play to find and use your app, as well as helping them to keep it updated.

Never forget to attach your apk to the release when tagging a new version, so that Izzy can take it and make it available via a F-Droid client to your users (see #3)

### CODE REVIEW

**Comment by Helltar** [comment]
Okay, but I see it's quite an old version, need to update, I did not see how IzzyOnDroid works, automatically or not, I'll look sometime

**Comment by Poussinou** [comment]
@Helltar the version was from 05/06/2022, it's the last one, isn't it? Would it be possible to always attach apks to the release form now on?

@IzzySoft FYI, there is an apk now in the release section in the last release from one week ago. And the signing key is changing.

**Comment by Helltar** [comment]
@Poussinou, sorry, yes, the latest version, it seemed to me that the version is old because of the old screenshots, and we have different regional settings, I thought it was May :)

Yes, now I'm attaching the apk.

**Comment by IzzySoft** [comment]
You could set up [Fastlane structures](https://gitlab.com/-/snippets/1895688) which my updater then can pick up, yes. I can send you what is currently set up with my repo to get you started with that: [anpaside_fastlane.zip](https://github.com/Helltar/ANPASIDE/files/8894849/anpaside_fastlane.zip) Contents of that ZIP should go to the repo root. Simply adjust/replace what you need before committing :wink:

For formatting hints on `full_description.txt`, see [my wiki here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane). What I've attached are already the files resulting from conversion to HTML.

**Comment by Helltar** [comment]
Added, 4fec342. @IzzySoft, i couldn't find how to change the author name on the page? (to just _Helltar_)

**Comment by IzzySoft** [comment]
Thanks! Adjusted the config and just did an initial pull. Do you want me to remove the German description, as you didn't keep it? My updater just adds/replaces "new things", but doesn't remove translations.

As for `AuthorName`: that's part of the local metadata file so you didn't see it. I've adjusted it as requested – so with the next sync around 6 pm UTC, all updates should become visible. Note that I've now set to take `full_description` without reformatting as you kept HTML, which is totally fine; just should you wish to switch to a different formatting (see [my wiki here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for options), please let me know in advance to I can adjust (before it looks weird :see_no_evil:).

**Comment by Helltar** [comment]
> Do you want me to remove the German description, as you didn't keep it?

No, I just need a translator, I'm not sure if it's correct (added, but I don't know how "machine" it look ae12b50)

**Comment by IzzySoft** [comment]
Hm, not sure how you can verify that – other than by trusting a native speaker: looked good to me. Looking at it again: seems like it originates from some Google Translate, but at least the link in line 2 seems to have been inserted by me (I normally don't use that "formal language", so the translation was not mine, but it looks OK; I've compared it to EN and RU – though I must admit my Russian is quite rudimentary).

**Pull request merged**
